#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "QRTechNode.h"
#include "QRMicroResearch.h"
#include "QRTypes.h"
#include "QRResearchComponent.generated.h"

class UQRTechNode;
class UQRMicroResearchDefinition;
class UQRInventoryComponent;

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnTechNodeUnlocked, FName, TechNodeId);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnMicroResearchStacked, FName, MicroResearchId, int32, NewStackCount);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnResearchQueued, FName, MicroResearchId);

// Manages all research progress, tech node states, and micro-research stacking for a colony
UCLASS(ClassGroup=(QuietRift), meta=(BlueprintSpawnableComponent))
class QRCRAFTINGRESEARCH_API UQRResearchComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UQRResearchComponent();

	// ── State ────────────────────────────────
	UPROPERTY(BlueprintReadOnly, Replicated, Category = "Research")
	TArray<FQRTechNodeRuntime> TechNodeStates;

	UPROPERTY(BlueprintReadOnly, Replicated, Category = "Research")
	TArray<FQRMicroResearchRuntime> MicroResearchStates;

	// Current active micro-research queue (ordered)
	UPROPERTY(BlueprintReadOnly, Replicated, Category = "Research")
	TArray<FName> MicroResearchQueue;

	// Research points per second generated by researchers
	UPROPERTY(BlueprintReadOnly, Replicated, Category = "Research")
	float ResearchPointsPerSecond = 0.0f;

	// ── Events ───────────────────────────────
	UPROPERTY(BlueprintAssignable, Category = "Research|Events")
	FOnTechNodeUnlocked OnTechNodeUnlocked;

	UPROPERTY(BlueprintAssignable, Category = "Research|Events")
	FOnMicroResearchStacked OnMicroResearchStacked;

	UPROPERTY(BlueprintAssignable, Category = "Research|Events")
	FOnResearchQueued OnResearchQueued;

	// ── Tech Tree ────────────────────────────
	UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly, Category = "Research")
	void InitializeTechNodes(const TArray<UQRTechNode*>& AllNodes);

	UFUNCTION(BlueprintPure, Category = "Research")
	EQRTechNodeState GetTechNodeState(FName NodeId) const;

	UFUNCTION(BlueprintPure, Category = "Research")
	bool IsTechUnlocked(FName NodeId) const;

	UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly, Category = "Research")
	bool DeliverReferenceComponent(FName ReferenceComponentId);

	// Force-unlock a node by ID, bypassing prerequisites and research costs.
	// For debug / cheat use only — do not call from gameplay code.
	UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly, Category = "Research")
	void ForceUnlockTechNode(FName NodeId);

	UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly, Category = "Research")
	void AddResearchPoints(float Points, EQRResearchFamily Family);

	// ── Micro-Research ───────────────────────
	UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly, Category = "Research")
	bool QueueMicroResearch(FName MicroResearchId, UQRInventoryComponent* CostSource);

	UFUNCTION(BlueprintPure, Category = "Research")
	int32 GetMicroResearchStacks(FName MicroResearchId) const;

	UFUNCTION(BlueprintPure, Category = "Research")
	float GetMicroResearchMultiplier(FName MicroResearchId) const;

	// ── Codex ────────────────────────────────
	// Server-authoritative; not replicated (UE 5.7+ disallows replicated TMaps).
	// Clients query via the BlueprintPure helpers below.
	UPROPERTY(BlueprintReadOnly, Category = "Codex")
	TMap<FName, EQRCodexDiscoveryState> CodexStates;

	UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly, Category = "Codex")
	void AdvanceCodexState(FName SpeciesOrItemId, EQRCodexDiscoveryState NewState);

	UFUNCTION(BlueprintPure, Category = "Codex")
	EQRCodexDiscoveryState GetCodexState(FName Id) const;

	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

private:
	// Cached reference to all node definitions (loaded at init)
	TMap<FName, const UQRTechNode*> NodeDefinitions;
	TMap<FName, const UQRMicroResearchDefinition*> MicroResearchDefinitions;

	void TickResearchQueue(float DeltaTime);
	void TryUnlockNode(FQRTechNodeRuntime& Runtime);
	bool ArePrerequisitesMet(const UQRTechNode* Node) const;
};
