#include "QRGameplayTags.h"

namespace QRGameplayTags
{
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Food,               "Item.Category.Food")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Tool,               "Item.Category.Tool")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Weapon,             "Item.Category.Weapon")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Ammo,               "Item.Category.Ammo")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Component,          "Item.Category.Component")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_ReferenceComponent, "Item.Category.ReferenceComponent")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Resource,           "Item.Category.Resource")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Medicine,           "Item.Category.Medicine")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Clothing,           "Item.Category.Clothing")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Seed,               "Item.Category.Seed")

	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_Unknown,           "Food.Edibility.Unknown")
	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_Safe,              "Food.Edibility.Safe")
	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_Toxic,             "Food.Edibility.Toxic")
	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_MustCook,          "Food.Edibility.MustCook")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Fresh,                 "Food.Spoil.Fresh")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Aging,                 "Food.Spoil.Aging")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Spoiled,               "Food.Spoil.Spoiled")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Preserved,             "Food.Spoil.Preserved")

	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Food,             "Research.Family.Food")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Water,            "Research.Family.Water")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Medicine,         "Research.Family.Medicine")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Materials,        "Research.Family.Materials")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Metalwork,        "Research.Family.Metalwork")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Electronics,      "Research.Family.Electronics")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Ecology,          "Research.Family.Ecology")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Remnant,          "Research.Family.Remnant")

	UE_DEFINE_GAMEPLAY_TAG(Status_Bleeding,                  "Status.Injury.Bleeding")
	UE_DEFINE_GAMEPLAY_TAG(Status_Fracture,                  "Status.Injury.Fracture")
	UE_DEFINE_GAMEPLAY_TAG(Status_Infection,                 "Status.Injury.Infection")
	UE_DEFINE_GAMEPLAY_TAG(Status_Concussion,                "Status.Injury.Concussion")
	UE_DEFINE_GAMEPLAY_TAG(Status_Toxin,                     "Status.Injury.Toxin")
	UE_DEFINE_GAMEPLAY_TAG(Status_Exhausted,                 "Status.Condition.Exhausted")
	UE_DEFINE_GAMEPLAY_TAG(Status_Hypothermia,               "Status.Condition.Hypothermia")
	UE_DEFINE_GAMEPLAY_TAG(Status_Hungry,                    "Status.Need.Hungry")
	UE_DEFINE_GAMEPLAY_TAG(Status_Starving,                  "Status.Need.Starving")
	UE_DEFINE_GAMEPLAY_TAG(Status_Thirsty,                   "Status.Need.Thirsty")
	UE_DEFINE_GAMEPLAY_TAG(Status_Dehydrated,                "Status.Need.Dehydrated")

	UE_DEFINE_GAMEPLAY_TAG(Role_Gatherer,                    "Role.Gatherer")
	UE_DEFINE_GAMEPLAY_TAG(Role_Hauler,                      "Role.Hauler")
	UE_DEFINE_GAMEPLAY_TAG(Role_Cook,                        "Role.Cook")
	UE_DEFINE_GAMEPLAY_TAG(Role_Builder,                     "Role.Builder")
	UE_DEFINE_GAMEPLAY_TAG(Role_Miner,                       "Role.Miner")
	UE_DEFINE_GAMEPLAY_TAG(Role_Guard,                       "Role.Guard")
	UE_DEFINE_GAMEPLAY_TAG(Role_Researcher,                  "Role.Researcher")
	UE_DEFINE_GAMEPLAY_TAG(Role_Medic,                       "Role.Medic")
	UE_DEFINE_GAMEPLAY_TAG(Role_Scout,                       "Role.Scout")
	UE_DEFINE_GAMEPLAY_TAG(Role_Farmer,                      "Role.Farmer")
	UE_DEFINE_GAMEPLAY_TAG(Role_Engineer,                    "Role.Engineer")
	UE_DEFINE_GAMEPLAY_TAG(Role_Leader,                      "Role.Leader")

	UE_DEFINE_GAMEPLAY_TAG(Faction_Player,                   "Faction.Player")
	UE_DEFINE_GAMEPLAY_TAG(Faction_EngineerCompact,          "Faction.EngineerCompact")
	UE_DEFINE_GAMEPLAY_TAG(Faction_Remnant,                  "Faction.Remnant")
	UE_DEFINE_GAMEPLAY_TAG(Faction_Hostile_Generic,          "Faction.Hostile.Generic")

	UE_DEFINE_GAMEPLAY_TAG(Biome_Forest,                     "Biome.Forest")
	UE_DEFINE_GAMEPLAY_TAG(Biome_Grassland,                  "Biome.Grassland")
	UE_DEFINE_GAMEPLAY_TAG(Biome_BurnZone,                   "Biome.BurnZone")
	UE_DEFINE_GAMEPLAY_TAG(Biome_Swamp,                      "Biome.Swamp")
	UE_DEFINE_GAMEPLAY_TAG(Biome_Cave,                       "Biome.Cave")
	UE_DEFINE_GAMEPLAY_TAG(Biome_RockyHighland,              "Biome.RockyHighland")
	UE_DEFINE_GAMEPLAY_TAG(Biome_RemnantSite,                "Biome.RemnantSite")
	UE_DEFINE_GAMEPLAY_TAG(Biome_AbandonedSite,              "Biome.AbandonedSite")
	UE_DEFINE_GAMEPLAY_TAG(Biome_Ravine,                     "Biome.Ravine")

	UE_DEFINE_GAMEPLAY_TAG(Station_Workbench,                "Station.Workbench")
	UE_DEFINE_GAMEPLAY_TAG(Station_AnvilForge,               "Station.AnvilForge")
	UE_DEFINE_GAMEPLAY_TAG(Station_Kiln,                     "Station.Kiln")
	UE_DEFINE_GAMEPLAY_TAG(Station_LogYard,                  "Station.LogYard")
	UE_DEFINE_GAMEPLAY_TAG(Station_StonePile,                "Station.StonePile")
	UE_DEFINE_GAMEPLAY_TAG(Station_Pantry,                   "Station.Pantry")
	UE_DEFINE_GAMEPLAY_TAG(Station_ScrapHeap,                "Station.ScrapHeap")
	UE_DEFINE_GAMEPLAY_TAG(Station_CartographyBoard,         "Station.CartographyBoard")
	UE_DEFINE_GAMEPLAY_TAG(Station_WeaponRack,               "Station.WeaponRack")
	UE_DEFINE_GAMEPLAY_TAG(Station_Generator,                "Station.Generator")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Wood,              "Depot.Category.Wood")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Stone,             "Depot.Category.Stone")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Food,              "Depot.Category.Food")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Scrap,             "Depot.Category.Scrap")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Fuel,              "Depot.Category.Fuel")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Component,         "Depot.Category.Component")

	UE_DEFINE_GAMEPLAY_TAG(Threat_Predator,                  "Threat.Predator")
	UE_DEFINE_GAMEPLAY_TAG(Threat_Raid,                      "Threat.Raid")
	UE_DEFINE_GAMEPLAY_TAG(Threat_Remnant,                   "Threat.Remnant")
	UE_DEFINE_GAMEPLAY_TAG(Threat_Environmental,             "Threat.Environmental")

	UE_DEFINE_GAMEPLAY_TAG(Ending_Rescue,                    "Ending.Rescue")
	UE_DEFINE_GAMEPLAY_TAG(Ending_Escape,                    "Ending.Escape")
	UE_DEFINE_GAMEPLAY_TAG(Ending_Settlement,                "Ending.Settlement")
}
