#include "QRGameplayTags.h"

namespace QRGameplayTags
{
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Food,               "Item.Category.Food")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Tool,               "Item.Category.Tool")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Weapon,             "Item.Category.Weapon")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Ammo,               "Item.Category.Ammo")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Component,          "Item.Category.Component")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_ReferenceComponent, "Item.Category.ReferenceComponent")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Resource,           "Item.Category.Resource")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Medicine,           "Item.Category.Medicine")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Clothing,           "Item.Category.Clothing")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_ChestRig,           "Item.Category.ChestRig")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Backpack,           "Item.Category.Backpack")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Cosmetic,           "Item.Category.Cosmetic")
	UE_DEFINE_GAMEPLAY_TAG(Item_Category_Seed,               "Item.Category.Seed")

	UE_DEFINE_GAMEPLAY_TAG(Equipment_Slot_ChestRig,          "Equipment.Slot.ChestRig")
	UE_DEFINE_GAMEPLAY_TAG(Equipment_Slot_Backpack,          "Equipment.Slot.Backpack")

	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_Unknown,           "Food.Edibility.Unknown")
	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_Safe,              "Food.Edibility.Safe")
	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_Toxic,             "Food.Edibility.Toxic")
	UE_DEFINE_GAMEPLAY_TAG(Food_Edibility_MustCook,          "Food.Edibility.MustCook")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Fresh,                 "Food.Spoil.Fresh")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Aging,                 "Food.Spoil.Aging")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Spoiled,               "Food.Spoil.Spoiled")
	UE_DEFINE_GAMEPLAY_TAG(Food_Spoil_Preserved,             "Food.Spoil.Preserved")

	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Food,             "Research.Family.Food")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Water,            "Research.Family.Water")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Medicine,         "Research.Family.Medicine")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Materials,        "Research.Family.Materials")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Metalwork,        "Research.Family.Metalwork")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Electronics,      "Research.Family.Electronics")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Ecology,          "Research.Family.Ecology")
	UE_DEFINE_GAMEPLAY_TAG(Research_Family_Remnant,          "Research.Family.Remnant")

	UE_DEFINE_GAMEPLAY_TAG(Status_Bleeding,                  "Status.Injury.Bleeding")
	UE_DEFINE_GAMEPLAY_TAG(Status_Fracture,                  "Status.Injury.Fracture")
	UE_DEFINE_GAMEPLAY_TAG(Status_Infection,                 "Status.Injury.Infection")
	UE_DEFINE_GAMEPLAY_TAG(Status_Concussion,                "Status.Injury.Concussion")
	UE_DEFINE_GAMEPLAY_TAG(Status_Toxin,                     "Status.Injury.Toxin")
	UE_DEFINE_GAMEPLAY_TAG(Status_Exhausted,                 "Status.Condition.Exhausted")
	UE_DEFINE_GAMEPLAY_TAG(Status_Hypothermia,               "Status.Condition.Hypothermia")
	UE_DEFINE_GAMEPLAY_TAG(Status_Hungry,                    "Status.Need.Hungry")
	UE_DEFINE_GAMEPLAY_TAG(Status_Starving,                  "Status.Need.Starving")
	UE_DEFINE_GAMEPLAY_TAG(Status_Thirsty,                   "Status.Need.Thirsty")
	UE_DEFINE_GAMEPLAY_TAG(Status_Dehydrated,                "Status.Need.Dehydrated")

	UE_DEFINE_GAMEPLAY_TAG(Role_Gatherer,                    "Role.Gatherer")
	UE_DEFINE_GAMEPLAY_TAG(Role_Hauler,                      "Role.Hauler")
	UE_DEFINE_GAMEPLAY_TAG(Role_Cook,                        "Role.Cook")
	UE_DEFINE_GAMEPLAY_TAG(Role_Builder,                     "Role.Builder")
	UE_DEFINE_GAMEPLAY_TAG(Role_Miner,                       "Role.Miner")
	UE_DEFINE_GAMEPLAY_TAG(Role_Guard,                       "Role.Guard")
	UE_DEFINE_GAMEPLAY_TAG(Role_Researcher,                  "Role.Researcher")
	UE_DEFINE_GAMEPLAY_TAG(Role_Medic,                       "Role.Medic")
	UE_DEFINE_GAMEPLAY_TAG(Role_Scout,                       "Role.Scout")
	UE_DEFINE_GAMEPLAY_TAG(Role_Farmer,                      "Role.Farmer")
	UE_DEFINE_GAMEPLAY_TAG(Role_Engineer,                    "Role.Engineer")
	UE_DEFINE_GAMEPLAY_TAG(Role_Leader,                      "Role.Leader")

	UE_DEFINE_GAMEPLAY_TAG(Faction_Player,                   "Faction.Player")
	UE_DEFINE_GAMEPLAY_TAG(Faction_EngineerCompact,          "Faction.EngineerCompact")
	UE_DEFINE_GAMEPLAY_TAG(Faction_Remnant,                  "Faction.Remnant")
	UE_DEFINE_GAMEPLAY_TAG(Faction_Hostile_Generic,          "Faction.Hostile.Generic")
	UE_DEFINE_GAMEPLAY_TAG(Faction_Vanguard,                 "Faction.Vanguard")
	UE_DEFINE_GAMEPLAY_TAG(Faction_Vanguard_Satellite,       "Faction.Vanguard.Satellite")
	UE_DEFINE_GAMEPLAY_TAG(Threat_Vanguard,                  "Threat.Vanguard")

	UE_DEFINE_GAMEPLAY_TAG(Biome_BasaltShelf,                "Biome.BasaltShelf")
	UE_DEFINE_GAMEPLAY_TAG(Biome_WindPlains,                 "Biome.WindPlains")
	UE_DEFINE_GAMEPLAY_TAG(Biome_WetBasins,                  "Biome.WetBasins")
	UE_DEFINE_GAMEPLAY_TAG(Biome_ColdBasins,                 "Biome.ColdBasins")
	UE_DEFINE_GAMEPLAY_TAG(Biome_CraterFloors,               "Biome.CraterFloors")
	UE_DEFINE_GAMEPLAY_TAG(Biome_CraterWalls,                "Biome.CraterWalls")
	UE_DEFINE_GAMEPLAY_TAG(Biome_ThermalCracks,              "Biome.ThermalCracks")
	UE_DEFINE_GAMEPLAY_TAG(Biome_GlassDunes,                 "Biome.GlassDunes")
	UE_DEFINE_GAMEPLAY_TAG(Biome_MagneticRidges,             "Biome.MagneticRidges")
	UE_DEFINE_GAMEPLAY_TAG(Biome_MossFields,                 "Biome.MossFields")
	UE_DEFINE_GAMEPLAY_TAG(Biome_HighRims,                   "Biome.HighRims")
	UE_DEFINE_GAMEPLAY_TAG(Biome_MeltlineEdges,              "Biome.MeltlineEdges")
	UE_DEFINE_GAMEPLAY_TAG(Biome_ShallowFens,                "Biome.ShallowFens")
	UE_DEFINE_GAMEPLAY_TAG(Biome_RidgeShadows,               "Biome.RidgeShadows")
	UE_DEFINE_GAMEPLAY_TAG(Biome_CanyonWebs,                 "Biome.CanyonWebs")
	UE_DEFINE_GAMEPLAY_TAG(Biome_VentRims,                   "Biome.VentRims")
	UE_DEFINE_GAMEPLAY_TAG(Biome_IronBasalt,                 "Biome.IronBasalt")
	UE_DEFINE_GAMEPLAY_TAG(Biome_IceCaves,                   "Biome.IceCaves")
	UE_DEFINE_GAMEPLAY_TAG(Biome_ShadowFens,                 "Biome.ShadowFens")
	UE_DEFINE_GAMEPLAY_TAG(Biome_RemnantSite,                "Biome.RemnantSite")
	UE_DEFINE_GAMEPLAY_TAG(Biome_AbandonedStructures,        "Biome.AbandonedStructures")
	UE_DEFINE_GAMEPLAY_TAG(Biome_Caves,                      "Biome.Caves")

	UE_DEFINE_GAMEPLAY_TAG(Flora_LatticeBulb,                "Flora.LatticeBulb")
	UE_DEFINE_GAMEPLAY_TAG(Flora_SpiralReed,                 "Flora.SpiralReed")
	UE_DEFINE_GAMEPLAY_TAG(Flora_MeltpodRind,                "Flora.MeltpodRind")
	UE_DEFINE_GAMEPLAY_TAG(Flora_EmberLace,                  "Flora.EmberLace")
	UE_DEFINE_GAMEPLAY_TAG(Flora_NullmintNodes,              "Flora.NullmintNodes")
	UE_DEFINE_GAMEPLAY_TAG(Flora_KnifeleafFan,               "Flora.KnifeleafFan")
	UE_DEFINE_GAMEPLAY_TAG(Flora_ResinChimney,               "Flora.ResinChimney")
	UE_DEFINE_GAMEPLAY_TAG(Flora_SilkCystVine,               "Flora.SilkCystVine")
	UE_DEFINE_GAMEPLAY_TAG(Flora_MawcapBloom,                "Flora.MawcapBloom")
	UE_DEFINE_GAMEPLAY_TAG(Flora_ThreadmoldSheet,            "Flora.ThreadmoldSheet")
	UE_DEFINE_GAMEPLAY_TAG(Flora_FerricBloom,                "Flora.FerricBloom")
	UE_DEFINE_GAMEPLAY_TAG(Flora_CrystalLichen,              "Flora.CrystalLichen")
	UE_DEFINE_GAMEPLAY_TAG(Flora_CinderThorn,                "Flora.CinderThorn")
	UE_DEFINE_GAMEPLAY_TAG(Flora_IronbrineCups,              "Flora.IronbrineCups")
	UE_DEFINE_GAMEPLAY_TAG(Flora_GlasbarkTree,               "Flora.GlasbarkTree")
	UE_DEFINE_GAMEPLAY_TAG(Flora_SlagrootTree,               "Flora.SlagrootTree")
	UE_DEFINE_GAMEPLAY_TAG(Flora_VelvetspineTree,            "Flora.VelvetspineTree")
	UE_DEFINE_GAMEPLAY_TAG(Flora_AsterbarkTree,              "Flora.AsterbarkTree")

	UE_DEFINE_GAMEPLAY_TAG(Fauna_PebbleSkitter,              "Fauna.PebbleSkitter")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_GleamLarver,                "Fauna.GleamLarver")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_ShardbackGrazer,            "Fauna.ShardbackGrazer")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_SiltStrider,                "Fauna.SiltStrider")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_PillarbackHauler,           "Fauna.PillarbackHauler")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_BasinTreader,               "Fauna.BasinTreader")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_NestweaverDrifter,          "Fauna.NestweaverDrifter")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_MilkbladderHerdling,        "Fauna.MilkbladderHerdling")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_BoneLantern,                "Fauna.BoneLantern")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_LatchfinMite,               "Fauna.LatchfinMite")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_Crackrunner,                "Fauna.Crackrunner")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_RidgeCourser,               "Fauna.RidgeCourser")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_VaultbackDray,              "Fauna.VaultbackDray")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_TetherbackPackgrazer,       "Fauna.TetherbackPackgrazer")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_SutureWisp,                 "Fauna.SutureWisp")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_NeedleMaw,                  "Fauna.NeedleMaw")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_DriftStalker,               "Fauna.DriftStalker")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_VaneRippers,                "Fauna.VaneRippers")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_GlassjawCluster,            "Fauna.GlassjawCluster")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_SiltHounds,                 "Fauna.SiltHounds")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_TrenchDiggers,              "Fauna.TrenchDiggers")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_CarrionChoir,               "Fauna.CarrionChoir")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_FogleechSwarm,              "Fauna.FogleechSwarm")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_IronstagStalker,            "Fauna.IronstagStalker")
	UE_DEFINE_GAMEPLAY_TAG(Fauna_ShellmawAmbusher,           "Fauna.ShellmawAmbusher")

	UE_DEFINE_GAMEPLAY_TAG(Station_Workbench,                "Station.Workbench")
	UE_DEFINE_GAMEPLAY_TAG(Station_AnvilForge,               "Station.AnvilForge")
	UE_DEFINE_GAMEPLAY_TAG(Station_Kiln,                     "Station.Kiln")
	UE_DEFINE_GAMEPLAY_TAG(Station_LogYard,                  "Station.LogYard")
	UE_DEFINE_GAMEPLAY_TAG(Station_StonePile,                "Station.StonePile")
	UE_DEFINE_GAMEPLAY_TAG(Station_Pantry,                   "Station.Pantry")
	UE_DEFINE_GAMEPLAY_TAG(Station_ScrapHeap,                "Station.ScrapHeap")
	UE_DEFINE_GAMEPLAY_TAG(Station_CartographyBoard,         "Station.CartographyBoard")
	UE_DEFINE_GAMEPLAY_TAG(Station_WeaponRack,               "Station.WeaponRack")
	UE_DEFINE_GAMEPLAY_TAG(Station_Generator,                "Station.Generator")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Wood,              "Depot.Category.Wood")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Stone,             "Depot.Category.Stone")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Food,              "Depot.Category.Food")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Scrap,             "Depot.Category.Scrap")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Fuel,              "Depot.Category.Fuel")
	UE_DEFINE_GAMEPLAY_TAG(Depot_Category_Component,         "Depot.Category.Component")

	UE_DEFINE_GAMEPLAY_TAG(Threat_Predator,                  "Threat.Predator")
	UE_DEFINE_GAMEPLAY_TAG(Threat_Raid,                      "Threat.Raid")
	UE_DEFINE_GAMEPLAY_TAG(Threat_Remnant,                   "Threat.Remnant")
	UE_DEFINE_GAMEPLAY_TAG(Threat_Environmental,             "Threat.Environmental")

	UE_DEFINE_GAMEPLAY_TAG(Ending_Rescue,                    "Ending.Rescue")
	UE_DEFINE_GAMEPLAY_TAG(Ending_Escape,                    "Ending.Escape")
	UE_DEFINE_GAMEPLAY_TAG(Ending_Settlement,                "Ending.Settlement")

	UE_DEFINE_GAMEPLAY_TAG(Tool_Knife,                       "Tool.Knife")
	UE_DEFINE_GAMEPLAY_TAG(Tool_Axe,                         "Tool.Axe")
	UE_DEFINE_GAMEPLAY_TAG(Tool_HeavyAxe,                    "Tool.HeavyAxe")
	UE_DEFINE_GAMEPLAY_TAG(Tool_Gloves,                      "Tool.Gloves")
	UE_DEFINE_GAMEPLAY_TAG(Tool_Pickaxe,                     "Tool.Pickaxe")
	UE_DEFINE_GAMEPLAY_TAG(Tool_Sickle,                      "Tool.Sickle")

	UE_DEFINE_GAMEPLAY_TAG(Ammo_Dirty,                       "Ammo.Dirty")
	UE_DEFINE_GAMEPLAY_TAG(Ammo_Subsonic,                    "Ammo.Subsonic")
	UE_DEFINE_GAMEPLAY_TAG(Ammo_AP,                          "Ammo.AP")

	UE_DEFINE_GAMEPLAY_TAG(Weather_DustStorm,                "Weather.DustStorm")
	UE_DEFINE_GAMEPLAY_TAG(Weather_AcidRain,                 "Weather.AcidRain")
	UE_DEFINE_GAMEPLAY_TAG(Weather_VentEruption,             "Weather.VentEruption")
	UE_DEFINE_GAMEPLAY_TAG(Weather_HeatWave,                 "Weather.HeatWave")
	UE_DEFINE_GAMEPLAY_TAG(Weather_IceFog,                   "Weather.IceFog")
	UE_DEFINE_GAMEPLAY_TAG(Weather_MagneticStorm,            "Weather.MagneticStorm")

	UE_DEFINE_GAMEPLAY_TAG(Scent_Meat,                       "Scent.Meat")
	UE_DEFINE_GAMEPLAY_TAG(Scent_Blood,                      "Scent.Blood")
	UE_DEFINE_GAMEPLAY_TAG(Scent_Carrion,                    "Scent.Carrion")
}
