"""
Quiet Rift: Enigma -- Photoreal overhaul batch (Blender 4.x/5.x).

Round-trips every static-mesh FBX under Content/Meshes/ through the
fidelity toolkit (qr_blender_photoreal):

  import FBX
    -> read each slot's authored base colour (the palette survives)
    -> classify surface family from the slot name (metal / wood /
       rock / hide / fabric / leaf / crystal ...)
    -> rebuild it as a full procedural PBR node material
    -> organic categories get subdivision + noise displacement;
       hard-surface keeps machined edges (subdiv only, no displace)
    -> smart-UV atlas, bake BaseColor/Roughness/Normal
    -> re-export the FBX with the baked maps EMBEDDED, so UE's
       importer rebuilds the textured material automatically
       (qr_seed_items now imports materials+textures).

UCX_ collision meshes and SOCKET_ empties pass through untouched.
LODs are regenerated from the refined mesh (decimate) so their UVs
match the baked atlas.

Usage (headless -- works in a plain python that has the bpy module,
or via blender --background --python):
    python qr_photoreal_overhaul.py                # everything
    python qr_photoreal_overhaul.py walls weapons  # category filter
Optional env:
    QR_OVERHAUL_LIMIT=5   process at most N files per category (QA runs)

Deterministic: fixed noise seeds; re-runs produce identical maps.
Skips SK_* skeletal FBX (wildlife/player) -- those are regenerated by
their own rigged generators.
"""

import bpy
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from qr_blender_photoreal import (  # noqa: E402
    pbr_material, refine, bake_pbr,
)

MESH_ROOT = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "../../Content/Meshes"))

# Per-category treatment. displace layers are (kind, scale, strength_m).
# bake size scales with how much screen the category occupies.
CATEGORIES = {
    "walls_structures": dict(subdiv=1, displace=None, size=1024),
    "stations":         dict(subdiv=1, displace=None, size=1024),
    "weapons_assets":   dict(subdiv=1, displace=None, size=1024),
    "attachments_ammo": dict(subdiv=1, displace=None, size=512),
    "items_handheld":   dict(subdiv=1, displace=None, size=512),
    "food_assets":      dict(subdiv=2, displace=[("puff", 0.10, 0.006)], size=512),
    "cosmetic_clothing": dict(subdiv=1, displace=None, size=512),
    "rigs_packs":       dict(subdiv=1, displace=None, size=512),
    "poi_props":        dict(subdiv=1, displace=[("fine", 0.5, 0.03)], size=1024),
    "remnant_assets":   dict(subdiv=1, displace=None, size=1024),
    "vanguard_assets":  dict(subdiv=1, displace=None, size=1024),
    "wildlife":         dict(subdiv=2, displace=[("puff", 0.35, 0.02)], size=1024),
    # NOTE: Flora is deliberately ABSENT -- trees/grass/rocks are owned
    # by the rebuilt qr_generate_flora_assets generators (leaf-card
    # alpha textures + baked bark). Round-tripping them here would
    # replace the card materials with procedural rebakes and destroy
    # the alpha foliage.
}

# Slot-name keyword -> (pbr kind, roughness). First hit wins; the
# authored base colour of the slot is reused as the tint.
KIND_RULES = [
    (("glass", "crystal", "prism", "horn", "shard", "lens", "scope_glass"),
     ("crystal", 0.08)),
    (("leaf", "frond", "canopy", "petal", "grass", "blade_grass"),
     ("leaf_alien", 0.35)),
    (("bark", "trunk", "root", "branch"), ("bark", 0.8)),
    (("wood", "plank", "timber", "thatch"), ("wood_planks", 0.75)),
    (("rock", "stone", "boulder", "slag", "gravel"), ("rock", 0.9)),
    (("cloth", "fabric", "leather", "strap", "canvas", "rope"),
     ("fabric", 0.9)),
    (("hide", "skin", "flesh", "meat", "body", "tusk", "bone"),
     ("hide", 0.7)),
    (("soil", "dirt", "mud", "ash"), ("soil", 0.95)),
    # metals last: broad tokens
    (("steel", "gunmetal", "metal", "iron", "brass", "barrel", "alloy",
      "chrome", "tin"), ("metal_worn", 0.45)),
]
DEFAULT_KIND = ("metal_worn", 0.55)   # most props are machined salvage


def _kind_for_slot(slot_name):
    low = slot_name.lower()
    for tokens, kv in KIND_RULES:
        if any(t in low for t in tokens):
            return kv
    return DEFAULT_KIND


def _wipe():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def _primary_meshes():
    return [o for o in bpy.context.scene.objects
            if o.type == 'MESH'
            and not o.name.startswith("UCX_")
            and "_LOD" not in o.name]


def _lod_meshes():
    return [o for o in bpy.context.scene.objects
            if o.type == 'MESH' and "_LOD" in o.name]


def overhaul_fbx(fbx_path, treatment):
    name = os.path.splitext(os.path.basename(fbx_path))[0]
    _wipe()
    try:
        bpy.ops.import_scene.fbx(filepath=fbx_path)
    except Exception as e:
        print("  IMPORT FAILED {}: {}".format(name, e))
        return False

    primaries = _primary_meshes()
    if not primaries:
        print("  {}: no primary mesh -- skipped".format(name))
        return False

    # Join multi-part primaries so one atlas covers the asset.
    for o in bpy.context.selected_objects:
        o.select_set(False)
    for o in primaries:
        o.select_set(True)
    bpy.context.view_layer.objects.active = primaries[0]
    if len(primaries) > 1:
        bpy.ops.object.join()
    obj = bpy.context.view_layer.objects.active
    obj.name = name

    # Rebuild each slot as procedural PBR, keeping the authored colour.
    for idx, mat in enumerate(list(obj.data.materials)):
        if mat is None:
            continue
        tint = (0.5, 0.5, 0.5)
        if mat.use_nodes:
            bsdf = mat.node_tree.nodes.get("Principled BSDF")
            if bsdf:
                c = bsdf.inputs["Base Color"].default_value
                tint = (c[0], c[1], c[2])
        kind, rough = _kind_for_slot(mat.name)
        pbr = pbr_material("QROH_{}_{}".format(name, idx), kind,
                           tint=tint, rough=rough)
        obj.data.materials[idx] = pbr

    refine(obj, subdiv=treatment.get("subdiv", 1),
           displace=treatment.get("displace"),
           smooth_angle=40)

    # Fresh atlas UVs (the refined geometry needs them anyway).
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.uv.smart_project(angle_limit=math.radians(66), island_margin=0.02)
    bpy.ops.object.mode_set(mode='OBJECT')

    tex_dir = os.path.join(os.path.dirname(fbx_path), "Textures")
    if not bake_pbr(obj, name, tex_dir,
                    size=treatment.get("size", 1024), samples=8):
        print("  {}: bake failed -- keeping original FBX".format(name))
        return False

    # Regenerate LODs from the refined mesh so UVs match the atlas.
    for old in _lod_meshes():
        bpy.data.objects.remove(old)
    lod = obj.copy()
    lod.data = obj.data.copy()
    lod.name = "{}_LOD1".format(name)
    bpy.context.collection.objects.link(lod)
    dec = lod.modifiers.new("Dec", 'DECIMATE')
    dec.ratio = 0.35
    bpy.context.view_layer.objects.active = lod
    bpy.ops.object.modifier_apply(modifier="Dec")

    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.export_scene.fbx(
        filepath=fbx_path,
        use_selection=True,
        global_scale=1.0,
        apply_scale_options='FBX_SCALE_ALL',
        axis_forward='-Z',
        axis_up='Y',
        bake_space_transform=True,
        mesh_smooth_type='FACE',
        path_mode='COPY',
        embed_textures=True,      # UE importer rebuilds textured material
    )
    print("  OK {}".format(name))
    return True


def main(category_filter=None, limit=0):
    print("=== qr_photoreal_overhaul ===")
    done = failed = 0
    for cat, treatment in CATEGORIES.items():
        if category_filter and not any(f.lower() in cat.lower()
                                       for f in category_filter):
            continue
        cat_dir = os.path.join(MESH_ROOT, cat)
        if not os.path.isdir(cat_dir):
            continue
        fbxes = []
        for root, _dirs, files in os.walk(cat_dir):
            for fn in sorted(files):
                if fn.lower().endswith(".fbx") and not fn.startswith("SK_"):
                    fbxes.append(os.path.join(root, fn))
        if limit:
            fbxes = fbxes[:limit]
        print("[{}] {} fbx".format(cat, len(fbxes)))
        for path in fbxes:
            if overhaul_fbx(path, treatment):
                done += 1
            else:
                failed += 1
    print("=== overhaul complete: {} ok, {} failed ===".format(done, failed))


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    # Under `blender --background --python script.py -- args`, argv
    # includes blender's own args before '--'.
    if "--" in sys.argv:
        args = sys.argv[sys.argv.index("--") + 1:]
    limit = int(os.environ.get("QR_OVERHAUL_LIMIT", "0"))
    main(category_filter=args or None, limit=limit)
