#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace QRGameplayTags
{
	// ── Item Category Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Food)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Tool)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Weapon)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Ammo)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Component)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_ReferenceComponent)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Resource)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Medicine)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Clothing)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Seed)

	// ── Food State Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_Unknown)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_Safe)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_Toxic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_MustCook)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Fresh)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Aging)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Spoiled)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Preserved)

	// ── Research Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Food)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Water)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Medicine)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Materials)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Metalwork)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Electronics)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Ecology)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Remnant)

	// ── Survival Status Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Bleeding)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Fracture)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Infection)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Concussion)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Toxin)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Exhausted)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Hypothermia)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Hungry)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Starving)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Thirsty)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dehydrated)

	// ── NPC Role Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Gatherer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Hauler)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Cook)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Builder)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Miner)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Guard)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Researcher)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Medic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Scout)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Farmer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Engineer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Leader)

	// ── Faction Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Player)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_EngineerCompact)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Remnant)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Hostile_Generic)

	// ── Biome Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_Forest)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_Grassland)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_BurnZone)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_Swamp)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_Cave)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_RockyHighland)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_RemnantSite)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_AbandonedSite)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_Ravine)

	// ── Station / Depot Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Workbench)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_AnvilForge)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Kiln)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_LogYard)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_StonePile)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Pantry)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_ScrapHeap)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_CartographyBoard)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_WeaponRack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Generator)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Wood)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Stone)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Food)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Scrap)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Fuel)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Component)

	// ── Threat Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Predator)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Raid)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Remnant)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Environmental)

	// ── Ending Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ending_Rescue)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ending_Escape)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ending_Settlement)
}
