#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace QRGameplayTags
{
	// ── Item Category Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Food)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Tool)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Weapon)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Ammo)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Component)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_ReferenceComponent)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Resource)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Medicine)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Clothing)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Seed)

	// ── Food State Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_Unknown)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_Safe)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_Toxic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Edibility_MustCook)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Fresh)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Aging)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Spoiled)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Food_Spoil_Preserved)

	// ── Research Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Food)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Water)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Medicine)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Materials)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Metalwork)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Electronics)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Ecology)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Research_Family_Remnant)

	// ── Survival Status Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Bleeding)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Fracture)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Infection)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Concussion)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Toxin)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Exhausted)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Hypothermia)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Hungry)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Starving)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Thirsty)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dehydrated)

	// ── NPC Role Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Gatherer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Hauler)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Cook)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Builder)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Miner)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Guard)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Researcher)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Medic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Scout)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Farmer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Engineer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Leader)

	// ── Faction Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Player)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_EngineerCompact)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Remnant)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Hostile_Generic)

	// ── Biome Tags (v1.5 canonical) ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_BasaltShelf)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_WindPlains)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_WetBasins)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_ColdBasins)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_CraterFloors)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_CraterWalls)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_ThermalCracks)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_GlassDunes)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_MagneticRidges)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_MossFields)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_HighRims)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_MeltlineEdges)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_ShallowFens)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_RidgeShadows)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_CanyonWebs)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_VentRims)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_IronBasalt)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_IceCaves)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_ShadowFens)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_RemnantSite)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_AbandonedStructures)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biome_Caves)

	// ── Flora Entity Tags (v1.5 canonical) ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_LatticeBulb)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_SpiralReed)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_MeltpodRind)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_EmberLace)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_NullmintNodes)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_KnifeleafFan)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_ResinChimney)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_SilkCystVine)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_MawcapBloom)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_ThreadmoldSheet)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_FerricBloom)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_CrystalLichen)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_CinderThorn)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_IronbrineCups)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_GlasbarkTree)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_SlagrootTree)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_VelvetspineTree)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flora_AsterbarkTree)

	// ── Fauna Entity Tags — Animals (v1.5 canonical) ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_PebbleSkitter)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_GleamLarver)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_ShardbackGrazer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_SiltStrider)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_PillarbackHauler)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_BasinTreader)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_NestweaverDrifter)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_MilkbladderHerdling)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_BoneLantern)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_LatchfinMite)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_Crackrunner)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_RidgeCourser)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_VaultbackDray)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_TetherbackPackgrazer)

	// ── Fauna Entity Tags — Predators (v1.5 canonical) ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_SutureWisp)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_NeedleMaw)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_DriftStalker)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_VaneRippers)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_GlassjawCluster)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_SiltHounds)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_TrenchDiggers)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_CarrionChoir)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_FogleechSwarm)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_IronstagStalker)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fauna_ShellmawAmbusher)

	// ── Station / Depot Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Workbench)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_AnvilForge)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Kiln)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_LogYard)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_StonePile)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Pantry)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_ScrapHeap)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_CartographyBoard)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_WeaponRack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Station_Generator)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Wood)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Stone)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Food)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Scrap)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Fuel)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Depot_Category_Component)

	// ── Threat Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Predator)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Raid)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Remnant)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Threat_Environmental)

	// ── Ending Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ending_Rescue)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ending_Escape)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ending_Settlement)

	// ── Tool Tags (for harvest gating) ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tool_Knife)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tool_Axe)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tool_HeavyAxe)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tool_Gloves)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tool_Pickaxe)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tool_Sickle)

	// ── Ammo Quality Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Dirty)       // Improvised / dirty ammo (×5 fouling)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Subsonic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_AP)          // Armor-piercing

	// ── Weather Event Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weather_DustStorm)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weather_AcidRain)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weather_VentEruption)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weather_HeatWave)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weather_IceFog)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weather_MagneticStorm)

	// ── Scent Tags ──
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scent_Meat)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scent_Blood)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scent_Carrion)
}
